# Generated by Django 4.1 on 2023-08-22 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gun', '0005_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gun',
            name='user',
        ),
    ]
