# Generated by Django 4.1 on 2023-08-22 18:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gun', '0006_remove_gun_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gun',
            name='user',
            field=models.ManyToManyField(related_name='guns_purchased', to=settings.AUTH_USER_MODEL),
        ),
    ]
