# Generated by Django 4.1 on 2023-08-22 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gun', '0007_gun_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gun',
            name='user',
        ),
    ]
