# Generated by Django 4.1 on 2023-08-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='lvl',
        ),
        migrations.AddField(
            model_name='customuser',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
